image: python:3.11-slim

stages:
  - format-lint
  - test

before_script:
  - apt-get update && apt-get install -y git
  - pip install pdm
  - pdm install
  - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY

format:
  stage: format-lint
  script:
    - pdm run isort . --profile black --check-only
    - pdm run black --check .

lint:
  stage: format-lint
  script:
    - pdm run flake8
    - pdm run mypy . --ignore-missing-imports

security:
  stage: format-lint
  script:
    - pdm run bandit -c .bandit.yml -r .

test:
  stage: test
  script:
    - pdm run python manage.py test
  needs: []