image: python:3.11-slim

stages:
  - format-lint
  - test

before_script:
  - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
  - export DB_NAME=$DB_NAME
  - export DB_USER=$DB_USER
  - export DB_PASSWORD=$DB_PASSWORD
  - export DB_HOST=$DB_HOST
  - export DB_PORT=$DB_PORT
  - apt-get update && apt-get install -y git
  - pip install poetry
  - poetry install --with dev

format:
  stage: format-lint
  script:
    - poetry run isort . --profile black --check-only
    - poetry run black --check .

lint:
  stage: format-lint
  script:
    - poetry run flake8 .
    - poetry run mypy .

security:
  stage: format-lint
  script:
    - poetry run bandit -c .bandit.yml -r .

test:
  stage: test
  services:
    - name: postgres:latest
      alias: db
  variables:
    POSTGRES_USER: $DB_USER
    POSTGRES_PASSWORD: $DB_PASSWORD
    POSTGRES_DB: "db"
  
  script:
    - apt-get update && apt-get install -y postgresql-client  # Install pg_isready
    - until pg_isready -h db -p 5432; do echo "Waiting for DB"; sleep 1; done
    - poetry run python manage.py test
  needs: []