image: python:3.11-slim

stages:
  - format-lint
  - test

before_script:
  - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
  - apt-get update && apt-get install -y git
  - pip install poetry
  - poetry install --with dev

format:
  stage: format-lint
  script:
    - poetry run isort . --profile black --check-only
    - poetry run black --check .

lint:
  stage: format-lint
  script:
    - poetry run flake8
    - poetry run mypy . --ignore-missing-imports

security:
  stage: format-lint
  script:
    - poetry run bandit -c .bandit.yml -r .

test:
  stage: test
  script:
    - poetry run python manage.py test
  needs: []