before_script:
  - pip install pdm
  - pdm install

code_quality:
  stage: code_quality
  script:
    - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
    - pdm run isort --profile=black --line-length=88 --check-only .
    - pdm run black --check .
    - pdm run mypy . --ignore-missing-imports
    - flake8 --extend-ignore=E203,W503 --max-line-length=88