image: python:3.11-slim

stages:
  - format-lint
  - test

before_script:
  - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
  - apt-get update && apt-get install -y git && apt-get install -y git netca
  - pip install poetry
  - poetry install --with dev

format:
  stage: format-lint
  script:
    - poetry run isort . --profile black --check-only
    - poetry run black --check .

lint:
  stage: format-lint
  script:
    - poetry run flake8 .
    - poetry run mypy .

security:
  stage: format-lint
  script:
    - poetry run bandit -c .bandit.yml -r .

test:
  stage: test
  services:
    - name: postgres:latest
      alias: db
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  script:
    - until nc -z db 5432; do echo "Waiting for DB"; sleep 1; done  # Waiting for database
    - poetry run python manage.py test
  needs: []