image: python:3.11-slim

stages:
  - code_quality

before_script:
  - apt-get update && apt-get install -y git  # For Debian/Ubuntu-based systems
  - pip install pdm
  - pdm install

code_quality:
  stage: code_quality
  script:
    - pwd
    - git status
    - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
    - pdm run pre-commit run --all-files