image: python:3.11-slim

stages:
  - code_quality

before_script:
  - pip install pdm
  - pdm install

code_quality:
  stage: code_quality
  script:
    - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
    - pdm run pre-commit run --all-files