image: python:3.11-slim

stages:
  - format-lint
  - test

before_script:
  - apt-get update && apt-get install -y git
  - pip install pdm
  - pdm install
  - pwd
  - git status
  - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY

pre_commit:
  stage: format-lint
  script:
    - pdm run pre-commit run --all-files

test:
  stage: test
  script:
    - pdm run python manage.py test
  needs: []