image: python:3.11-slim

stages:
  - format-lint
  - test

before_script:
  - apt-get update && apt-get install -y git
  - pip install pdm
  - pdm install
  - pwd
  - git status
  - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY

format:
  stage: format-lint
  script:
    - pdm run isort --check-only .
    - pdm run black --check .

lint:
  stage: format-lint
  script:
    - pdm run flake8
    - pdm run mypy

test:
  stage: test
  script:
    - pdm run python manage.py test
  needs: []