image: python:3.11-slim

stages:
  - format

before_script:
  - pip install pdm
  - pdm install

isort:
  stage: format
  script:
    - pdm run isort --profile=black --line-length=88 --check-only .

black:
  stage: format
  script:
    - pdm run black --check .