version: "3.8"

services:
  app:
    image: finance_tracker:1.0-dev
    build:
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command:
      [
        "poetry",
        "run",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000"
      ]
