version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: postgres_db
    ports:
      - "5433:5432"
    env_file:
      - .env
