[tool.poetry]
name = "finance-tracker"
version = "0.1.0"
description = "Tracking expenses and income"
authors = ["Iván González <ivan.gonzalez.prz@gmail.com>"]
license = "Proprietary"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
gunicorn = "^20.1.0"
Django = "4.2.4"
django-cors-headers = "4.2.0"
django-debug-toolbar = "4.2.0"
djangorestframework = "3.14.0"
python-decouple = "3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
