# Generated by Django 4.2.4 on 2023-09-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_currencycode_currencydata_alter_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transactions.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.tag'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
