# Generated by Django 4.2.4 on 2023-08-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_remove_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.CharField(max_length=255),
        ),
    ]
