# Generated by Django 4.2.4 on 2023-09-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_category_parent_alter_category_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
    ]
