# Generated by Django 4.2.4 on 2023-09-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_category_name_parentcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='transactions.parentcategory'),
        ),
    ]
