# Generated by Django 4.2.4 on 2023-09-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_category_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
    ]
