# Generated by Django 4.2.4 on 2023-09-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_rename_parent_category_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='brand',
            field=models.CharField(default='Brand', max_length=255, verbose_name='Brand'),
            preserve_default=False,
        ),
    ]
