# Generated by Django 4.2.4 on 2023-09-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_transaction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='transactions.tag', verbose_name='Tags'),
        ),
    ]
