# Generated by Django 4.2.4 on 2023-09-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transaction_type_transactioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=7),
        ),
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
    ]
